# Generated by Django 5.2 on 2025-05-21 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='section',
        ),
    ]
