# Generated by Django 5.2 on 2025-06-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0003_subject_section'),
    ]

    operations = [
    ]
