# Generated by Django 5.2 on 2025-06-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0004_assign_default_sections'),
        ('face_recognition_app', 'assign_default_sections'),
    ]

    operations = [
    ]
