# Generated by Django 5.2 on 2025-06-06 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0005_merge_20250605_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='face_recognition_app.section'),
            preserve_default=False,
        ),
    ]
