# Generated by Django 5.2 on 2025-06-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0007_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.IntegerField(),
        ),
    ]
